# Generated by Django 4.2 on 2023-07-07 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracoll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Poet'), ('S', 'Songwriter'), ('B', 'Band')], help_text='Typology of author', max_length=1)),
                ('name_of_author', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name_of_author'],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_title', models.CharField(max_length=100)),
                ('translated_content', models.TextField(max_length=2000)),
                ('original_text', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tracoll.text')),
            ],
            options={
                'ordering': ['translated_title'],
            },
        ),
        migrations.AddField(
            model_name='text',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tracoll.author'),
        ),
    ]
