# Generated by Django 4.2 on 2023-07-08 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_tracoll', '0002_author_translation_text_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='status',
            new_name='type_of_author',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='status',
            new_name='status_of_translation',
        ),
        migrations.AddField(
            model_name='translation',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
