# Generated by Django 4.2.3 on 2023-07-11 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracoll', '0005_alter_translation_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name_of_author'], 'permissions': (('can_watch_every_status', 'You can watch every text status'),)},
        ),
    ]
