# Generated by Django 4.2.3 on 2023-07-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracoll', '0006_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translation',
            options={'ordering': ['translated_title'], 'permissions': (('permession_of_edit_text_with_every_status', 'You can edit every text in every status'),)},
        ),
    ]
