# Generated by Django 4.2.3 on 2023-07-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracoll', '0007_alter_translation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translation',
            options={'ordering': ['translated_title'], 'permissions': (('permession_of_edit_text_with_every_status', 'You can edit every text in every status'), ('permission_of_add(W)_or_edit_a_collaborative_traslation(E)', 'You can add (W) or edit a collaborative traslation(E)'))},
        ),
    ]
