# Generated by Django 4.2.3 on 2023-07-15 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracoll', '0012_language_alter_text_original_language'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Language',
            new_name='Languageee',
        ),
        migrations.AlterModelOptions(
            name='languageee',
            options={'ordering': ['name_of_languageee']},
        ),
        migrations.RenameField(
            model_name='languageee',
            old_name='name_of_language',
            new_name='name_of_languageee',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='original_language',
            new_name='original_languageee',
        ),
    ]
