# Generated by Django 4.2.3 on 2023-07-15 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracoll', '0013_rename_language_languageee_alter_languageee_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='original_languageee',
            new_name='lingua',
        ),
    ]
