# Generated by Django 4.2 on 2023-07-16 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracoll', '0015_rename_languageee_language_alter_language_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='original_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tracoll.language'),
        ),
    ]
